services:
  autoqui:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: autoqui
    restart: always
    env_file:
      - ./backend/.env
    networks:
      - docker_internal

networks:
  docker_internal:
    external: true
