import { authService } from '../services/auth';
import { dbService } from '../services/db';
import { evolutionApi } from '../services/evolutionApi';
import { toast } from '../services/toast';

// @ts-ignore
window.copyToClipboard = (text: string, successMsg: string = 'Link copiado!') => {
    navigator.clipboard.writeText(text).then(() => {
        toast.success(successMsg);
    }).catch(err => {
        console.error('Erro ao copiar link:', err);
        toast.error('Erro ao copiar link.');
    });
};

// @ts-ignore
window.toggleStoreActive = async (companyId: string, storeId: string, active: boolean) => {
    try {
        const companyDoc = await dbService.get('companies', companyId);
        if (!companyDoc) return;

        const company = companyDoc as any;
        const stores = company.stores || [];
        const storeIndex = stores.findIndex((s: any) => s.id === storeId);

        if (storeIndex !== -1) {
            stores[storeIndex].active = active;
            await dbService.update('companies', companyId, { stores });
            toast.success(`Loja ${active ? 'ativada' : 'desativada'} com sucesso!`);
            setTimeout(() => location.reload(), 1000);
        }
    } catch (error) {
        console.error('Error toggling store status:', error);
        toast.error('Erro ao alterar status da loja.');
    }
};

export const Dashboard = async () => {
    const user = authService.getCurrentUser();

    if (!user) return '';

    let metrics = {
        messages: 0,
        payments: 0,
        orders_pending: 0,
        orders_paid: 0,
        today: 0,
        openai: {
            usage: 0,
            credits: 0,
            limit: 0
        }
    };

    let modulos: string[] = ['atendimento']; // Default
    let catalogMetrics: any = null;

    if (user?.role === 'admin') {
        modulos = ['atendimento', 'venda', 'agendamento', 'disparo']; // Admin sees all
        try {
            const companies = await dbService.getAll('companies');
            companies.forEach((c: any) => {
                if (c.metrics) {
                    metrics.messages += c.metrics.totalMessages || 0;
                    metrics.payments += c.metrics.totalPayments || 0;
                }
            });
            metrics.orders_pending = 15;
            metrics.orders_paid = 1200;

            // Fetch OpenAI billing settings (Admin side)
            const openaiBilling = await dbService.get('settings', 'openai') as any;
            if (openaiBilling) {
                metrics.openai = {
                    usage: openaiBilling.usage || 0,
                    credits: openaiBilling.credits || 0,
                    limit: openaiBilling.limit || 0
                };
            } else {
                // Initialize default if not found
                metrics.openai = { usage: 0, credits: 0, limit: 0 };
            }
        } catch (error) {
            console.error('Error fetching dashboard data:', error);
        }
    } else if (user?.companyId) {
        try {
            const companyDoc = await dbService.get('companies', user.companyId);
            const company = companyDoc as any;
            modulos = company?.modulos_ativos || ['atendimento'];

            // Count messages generated by IA
            if (modulos.includes('atendimento')) {
                const messages = await dbService.getAll('messages', {
                    field: 'empresaId',
                    operator: '==',
                    value: user.companyId
                });
                const userStoreIds = user.storeIds || (user.storeId ? [user.storeId] : []);
                metrics.messages = messages.filter((m: any) => {
                    if (m.role !== 'assistente') return false;
                    if (user.role === 'owner') return true;
                    return m.lojaId && userStoreIds.includes(m.lojaId);
                }).length;
            }


            // Compute total sales and orders metrics
            if (modulos.includes('venda') || modulos.includes('venda_catalogo')) {
                const orders = await dbService.getAll('pedidos', {
                    field: 'empresaId',
                    operator: '==',
                    value: user.companyId
                }) as any[];
                const userStoreIds = (user as any).storeIds || ((user as any).storeId ? [(user as any).storeId] : []);

                const filteredOrders = (user as any).role === 'owner'
                    ? orders
                    : orders.filter((o: any) => o.lojaId && userStoreIds.includes(o.lojaId));

                metrics.orders_pending = filteredOrders.filter((o: any) => {
                    const status = (o.status || 'em_montagem').toLowerCase();
                    const isTerminal = status === 'finalizado' || status === 'cancelado';
                    if (o.arquivado) return false;
                    return !isTerminal;
                }).length;
                metrics.orders_paid = filteredOrders.filter((o: any) => o.status === 'finalizado').length;

                let totalSales = 0;
                let ordersToday = 0;
                const today = new Date();
                today.setHours(0, 0, 0, 0);

                filteredOrders.forEach((o: any) => {
                    if (o.status === 'finalizado') {
                        totalSales += (o.value || o.total || 0);
                    }
                    const orderDate = o.criadoEm?.toDate ? o.criadoEm.toDate() : new Date(o.criadoEm || 0);
                    if (orderDate >= today) {
                        ordersToday++;
                    }
                });
                metrics.payments = totalSales;
                metrics.today = ordersToday;

                if (modulos.includes('venda_catalogo')) {
                    // ── Low stock products ──────────────────────────────────
                    const products = await dbService.getAll('products', {
                        field: 'companyId', operator: '==', value: user.companyId
                    }) as any[];
                    const lowStockProducts = products.filter((p: any) => p.stock != null && p.stock <= 5 && p.active !== false)
                        .sort((a: any, b: any) => (a.stock ?? 0) - (b.stock ?? 0))
                        .slice(0, 10);

                    // ── Top selling products (count items in catalog orders) ──
                    const salesMap: Map<string, { name: string; qty: number; revenue: number }> = new Map();
                    filteredOrders.forEach((o: any) => {
                        const items = Array.isArray(o.items) ? o.items : (Array.isArray(o.itens) ? o.itens : []);
                        items.forEach((i: any) => {
                            const name = i.name || i.item || 'Produto';
                            const qty = i.qty || i.quantidade || 1;
                            const price = i.price || i.preco || 0;
                            const cur = salesMap.get(name) || { name, qty: 0, revenue: 0 };
                            salesMap.set(name, { name, qty: cur.qty + qty, revenue: cur.revenue + (qty * price) });
                        });
                    });
                    const topProducts = Array.from(salesMap.values())
                        .sort((a, b) => b.qty - a.qty)
                        .slice(0, 5);

                    // ── Best hours (by count of orders) ──────────────────────
                    const hourMap: Map<number, number> = new Map();
                    filteredOrders.forEach((o: any) => {
                        const d = o.criadoEm?.toDate ? o.criadoEm.toDate() : new Date(o.criadoEm || 0);
                        const h = d.getHours();
                        hourMap.set(h, (hourMap.get(h) || 0) + 1);
                    });
                    const bestHours = Array.from(hourMap.entries())
                        .sort((a, b) => b[1] - a[1])
                        .slice(0, 3);

                    const avgTicket = metrics.orders_paid > 0 ? totalSales / metrics.orders_paid : 0;

                    catalogMetrics = { lowStockProducts, topProducts, bestHours, avgTicket, totalOrders: filteredOrders.length };
                }
            }

        } catch (error) {
            console.error('Error fetching dashboard data:', error);
        }
    }

    setTimeout(() => {
        if (user?.companyId) {
            setupStoreStatuses(user.companyId, user);
        }
    }, 100);

    return `
        <div class="page-header">
            <h2 class="page-title">Visão Geral (${user?.role === 'admin' ? 'Global' : 'Cliente'})</h2>
        </div>

        <div class="dashboard-grid">
            ${user.role === 'admin' ? `
                <div class="stats-card card" style="border: 1px solid rgba(16,185,129,0.3); background: rgba(16,185,129,0.02);">
                    <div class="stats-icon success"><i style="color: #ffffff8f;" class="fa-solid fa-coins"></i></div>
                    <div class="stats-info">
                        <span class="label">Créditos OpenAI</span><br>
                        <span class="value" style="color:var(--success);">$ ${metrics.openai.credits.toFixed(2)}</span>
                    </div>
                </div>
                <div class="stats-card card" style="border: 1px solid rgba(239,68,68,0.3); background: rgba(239,68,68,0.02);">
                    <div class="stats-icon danger"><i style="color: #ffffff8f;" class="fa-solid fa-file-invoice-dollar"></i></div>
                    <div class="stats-info">
                        <span class="label">Gasto OpenAI (Mês)</span><br>
                        <span class="value" style="color:var(--danger);">$ ${metrics.openai.usage.toFixed(2)}</span>
                    </div>
                </div>
            ` : ''}
            ${modulos.includes('atendimento') ? `
            <div class="stats-card card">
                <div class="stats-icon primary"><i style="color: #ffffff8f;" class="fa-solid fa-message"></i></div>
                <div class="stats-info">
                    <span class="label">Mensagens pela IA</span><br>
                    <span class="value">${metrics.messages}</span>
                </div>
            </div>` : ''}
            ${modulos.includes('venda') || modulos.includes('venda_catalogo') ? `
            <div class="stats-card card">
                <div class="stats-icon success"><i style="color: #ffffff8f;" class="fa-solid fa-money-bill"></i></div>
                <div class="stats-info">
                    <span class="label">Total em Vendas</span><br>
                    <span class="value">R\$ ${metrics.payments.toFixed(2)}</span>
                </div>
            </div>
            <div class="stats-card card">
                <div class="stats-icon warning"><i style="color: #ffffff8f;" class="fa-solid fa-hourglass-half"></i></div>
                <div class="stats-info">
                    <span class="label">Pedidos Pendentes</span><br>
                    <span class="value">${metrics.orders_pending}</span>
                </div>
            </div>
            <div class="stats-card card">
                <div class="stats-icon info"><i style="color: #ffffff8f;" class="fa-solid fa-box"></i></div>
                <div class="stats-info">
                    <span class="label">Pedidos Hoje</span><br>
                    <span class="value">${(metrics as any).today || 0}</span>
                </div>
            </div>
            ${catalogMetrics ? `
            <div class="stats-card card">
                <div class="stats-icon primary"><i style="color: #ffffff8f;" class="fa-solid fa-receipt"></i></div>
                <div class="stats-info">
                    <span class="label">Ticket Médio</span><br>
                    <span class="value">R\$ ${catalogMetrics.avgTicket.toFixed(2)}</span>
                </div>
            </div>
            ` : ''}
            ` : ''}
        </div>

        ${catalogMetrics ? `
        <div style="display:grid;grid-template-columns:repeat(auto-fit,minmax(280px,1fr));gap:1.25rem;margin-top:1.5rem;">

            <!-- Low Stock Alert -->
            <div class="card" style="border:1px solid rgba(239,68,68,0.3);background:rgba(239,68,68,0.03);">
                <h4 style="margin:0 0 1rem;display:flex;align-items:center;gap:8px;font-size:0.95rem;">
                    <i class="fa-solid fa-triangle-exclamation" style="color:#ef4444;"></i> Estoque Baixo
                </h4>
                ${catalogMetrics.lowStockProducts.length === 0
                ? `<p style="color:var(--text-muted);font-size:0.85rem;">Todos os produtos estão com estoque adequado.</p>`
                : catalogMetrics.lowStockProducts.map((p: any) => `
                        <div style="display:flex;justify-content:space-between;align-items:center;padding:6px 0;border-bottom:1px solid rgba(255,255,255,0.05);">
                            <span style="font-size:0.85rem;font-weight:500;">${p.name}</span>
                            <span class="badge ${p.stock === 0 ? 'danger' : 'warning'}">${p.stock === 0 ? 'Esgotado' : p.stock + ' un.'}</span>
                        </div>
                    `).join('')
            }
            </div>

            <!-- Top Selling Products -->
            <div class="card">
                <h4 style="margin:0 0 1rem;display:flex;align-items:center;gap:8px;font-size:0.95rem;">
                    <i class="fa-solid fa-trophy" style="color:#f59e0b;"></i> Top 5 Produtos
                </h4>
                ${catalogMetrics.topProducts.length === 0
                ? `<p style="color:var(--text-muted);font-size:0.85rem;">Nenhum pedido com itens ainda.</p>`
                : catalogMetrics.topProducts.map((p: any, i: number) => `
                        <div style="display:flex;align-items:center;gap:10px;padding:6px 0;border-bottom:1px solid rgba(255,255,255,0.05);">
                            <span style="font-size:1rem;font-weight:900;color:${i === 0 ? '#f59e0b' : i === 1 ? '#94a3b8' : i === 2 ? '#b45309' : 'var(--text-dim)'};min-width:20px;">${i + 1}</span>
                            <span style="flex:1;font-size:0.85rem;font-weight:500;">${p.name}</span>
                            <span style="font-size:0.8rem;color:var(--text-muted);">${p.qty} un.</span>
                            <span style="font-size:0.8rem;color:var(--success);">R\$ ${p.revenue.toFixed(2)}</span>
                        </div>
                    `).join('')
            }
            </div>

            <!-- Best Sales Hours -->
            <div class="card">
                <h4 style="margin:0 0 1rem;display:flex;align-items:center;gap:8px;font-size:0.95rem;">
                    <i class="fa-solid fa-chart-bar" style="color:var(--primary);"></i> Melhores Horários
                </h4>
                ${catalogMetrics.bestHours.length === 0
                ? `<p style="color:var(--text-muted);font-size:0.85rem;">Nenhum pedido registrado ainda.</p>`
                : catalogMetrics.bestHours.map(([h, count]: [number, number], i: number) => {
                    const maxCount = catalogMetrics.bestHours[0][1];
                    const pct = Math.round((count / maxCount) * 100);
                    return `
                            <div style="margin-bottom:10px;">
                                <div style="display:flex;justify-content:space-between;margin-bottom:4px;">
                                    <span style="font-size:0.85rem;font-weight:600;">${String(h).padStart(2, '0')}h – ${String(h + 1).padStart(2, '0')}h</span>
                                    <span style="font-size:0.8rem;color:var(--text-muted);">${count} pedido${count !== 1 ? 's' : ''}</span>
                                </div>
                                <div style="height:6px;background:rgba(255,255,255,0.08);border-radius:3px;overflow:hidden;">
                                    <div style="width:${pct}%;height:100%;background:${i === 0 ? 'var(--primary)' : 'rgba(99,102,241,0.4)'};border-radius:3px;"></div>
                                </div>
                            </div>
                        `;
                }).join('')
            }
            </div>

        </div>
        ` : ''}

        <div id="store-statuses-container"></div>
    `;

    async function setupStoreStatuses(companyId: string, currentUser: any) {
        const container = document.getElementById('store-statuses-container');
        if (!container) return;

        try {
            const companyDoc = await dbService.get('companies', companyId);
            const company = companyDoc as any;
            let stores = company?.stores || [];

            // Fetch all instances once to match with stores
            const instancesRaw = await dbService.getAll('instancias', { field: 'empresaId', operator: '==', value: companyId });
            const allInstances = instancesRaw as any[];

            if (currentUser.role !== 'owner') {
                const userStoreIds = currentUser.storeIds || (currentUser.storeId ? [currentUser.storeId] : []);
                stores = stores.filter((s: any) => userStoreIds.includes(s.id));
            }

            if (stores.length === 0) {
                container.innerHTML = `
                    <div class="card" style="margin-top: 1.5rem; background: rgba(239, 68, 68, 0.05); border: 1px solid rgba(239, 68, 68, 0.2);">
                        <h3 style="color: var(--danger);"><i class="fa-solid fa-triangle-exclamation"></i> Sistema Inoperante</h3>
                        <p style="color: var(--text-muted); font-size: 0.9rem;">Nenhuma loja encontrada ou associada a este usuário. O sistema não pode operar.</p>
                    </div>
                `;
                return;
            }

            let html = '';

            for (const store of stores) {
                let statusHtml = '';
                let isOnline = false;

                // Find instance for this store (Prioritize explicit link from store object)
                const inst = (store.instancia_id ? allInstances.find(i => i.id === store.instancia_id) : null) || allInstances.find(i => i.lojaId === store.id);
                const instanceName = inst?.nome;

                if (!inst || store.active === false) {
                    const reason = !inst ? 'Sem instância vinculada' : 'Loja desativada';
                    statusHtml = `
                        <div style="background: rgba(239, 68, 68, 0.1); padding: 1rem; border-radius: 8px; border-left: 4px solid var(--danger); margin-bottom: 1rem;">
                            <div style="display: flex; justify-content: space-between; align-items: center;">
                                <div>
                                    <p style="margin: 0; font-weight: 600; color: var(--danger);"><i class="fa-solid fa-circle-xmark"></i> Loja Inoperante</p>
                                    <p style="margin: 0.25rem 0 0 0; font-size: 0.85rem; color: var(--text-muted);">${reason}.</p>
                                </div>
                                <button class="btn-primary btn-sm" onclick="toggleStoreActive('${company.id}', '${store.id}', true)">
                                    <i class="fa-solid fa-play"></i> Ativar Loja
                                </button>
                            </div>
                        </div>
                    `;
                } else {
                    try {
                        const status = await evolutionApi.getInstanceStatus(instanceName);
                        // Be more flexible with state names
                        const connectedStates = ['open', 'connected', 'CONNECTED', 'ON'];
                        const isConnected = connectedStates.includes(status.state);

                        if (isConnected) {
                            isOnline = true;
                            statusHtml = `
                                <div style="background: rgba(34, 197, 94, 0.1); padding: 1rem; border-radius: 8px; border-left: 4px solid #22c55e; margin-bottom: 1rem;">
                                    <div style="display: flex; justify-content: space-between; align-items: center;">
                                        <div>
                                            <p style="margin: 0; font-weight: 600; color: #22c55e;"><i class="fa-solid fa-circle-check"></i> Instância Conectada</p>
                                            <p style="margin: 0.25rem 0 0 0; font-size: 0.85rem; color: var(--text-muted);">A IA e o WhatsApp estão online (Instância: ${instanceName}).</p>
                                        </div>
                                        <button class="btn-danger btn-sm" onclick="toggleStoreActive('${company.id}', '${store.id}', false)" style="background: #ef4444; color: white; border: none; padding: 5px 10px; border-radius: 4px; cursor: pointer;">
                                            <i class="fa-solid fa-power-off"></i> Desativar
                                        </button>
                                    </div>
                                </div>
                            `;
                        } else {
                            const qrData = await evolutionApi.getQRCode(instanceName);
                            statusHtml = `
                                <div style="background: rgba(239, 68, 68, 0.1); padding: 1rem; border-radius: 8px; border-left: 4px solid var(--danger); margin-bottom: 1rem;">
                                    <div style="display: flex; justify-content: space-between; align-items: flex-start; margin-bottom: 10px;">
                                        <div>
                                            <p style="margin: 0; font-weight: 600; color: var(--danger);"><i class="fa-solid fa-triangle-exclamation"></i> Instância Desconectada</p>
                                            <p style="margin: 0.25rem 0 0.5rem 0; font-size: 0.85rem; color: var(--text-muted);">Instância: <strong>${instanceName}</strong>. Escaneie o QR Code.</p>
                                        </div>
                                        <button class="btn-danger btn-sm" onclick="toggleStoreActive('${company.id}', '${store.id}', false)" style="background: #ef4444; color: white; border: none; padding: 5px 10px; border-radius: 4px; cursor: pointer;">
                                            <i class="fa-solid fa-power-off"></i> Desativar
                                        </button>
                                    </div>
                                    ${qrData?.base64 ? `<img src="${qrData.base64}" alt="QR" style="width:150px;height:150px;display:block;margin:0 auto;border-radius:8px; background: white; padding: 5px;">` : '<p style="font-size:0.8rem;text-align:center; padding: 20px;">QR Code indisponível no momento. Tente atualizar a página.</p>'}
                                </div>
                            `;
                        }
                    } catch (e) {
                        console.error('Error checking instance status in dashboard:', e);
                        statusHtml = `
                            <div style="background: rgba(245, 158, 11, 0.1); padding: 1rem; border-radius: 8px; border-left: 4px solid var(--warning); margin-bottom: 1rem;">
                                <p style="margin: 0; font-weight: 600; color: var(--warning);"><i class="fa-solid fa-circle-exclamation"></i> Erro de Comunicação</p>
                                <p style="margin: 0.25rem 0 0 0; font-size: 0.85rem; color: var(--text-muted);">Não foi possível verificar a instância: <strong>${instanceName}</strong>. Verifique sua conexão.</p>
                            </div>
                        `;
                    }
                }

                const freteAtivo = store.frete_ativo !== false; // default to true if undefined
                const isOperable = inst && store.active !== false;

                html += `
                    <div class="card" style="margin-top: 1.5rem; border: 1px solid ${isOnline ? 'rgba(34,197,94,0.3)' : 'rgba(239,68,68,0.3)'};">
                        <div style="display: flex; justify-content: space-between; align-items: flex-start; margin-bottom: 1rem;">
                            <div>
                                <h3 style="margin-bottom: 0.25rem;"><i class="fa-solid fa-store"></i> ${store.name}</h3>
                                <div style="display:flex; gap: 0.5rem; flex-wrap: wrap;">
                                    <span class="badge ${isOperable ? 'success' : 'danger'}">${isOperable ? 'Operante' : 'Inoperante'}</span>
                                    <span class="badge ${isOnline ? 'success' : 'warning'}">${isOnline ? 'WhatsApp Online' : 'WhatsApp Offline'}</span>
                                    <span class="badge ${freteAtivo ? 'success' : 'warning'}">${freteAtivo ? 'Frete Ativo' : 'Retirada Apenas'}</span>
                                </div>
                            </div>
                            <div style="display: flex; gap: 8px; flex-wrap: wrap;">
                                ${instanceName ? `
                                <button class="btn-secondary btn-sm" onclick="copyToClipboard('${window.location.origin}/qr/${instanceName}', 'Link de conexão copiado!')" title="Link para conectar WhatsApp" style="display: flex; align-items: center; gap: 6px; padding: 6px 10px; font-size: 0.75rem; border-radius: 6px; border-color: rgba(245, 158, 11, 0.3);">
                                    <i class="fa-solid fa-qrcode" style="font-size: 0.75rem; color: var(--warning);"></i> Link QR
                                </button>
                                ` : ''}
                                <a href="/catalog/${store.id}" target="_blank" class="btn-secondary btn-sm" style="text-decoration: none; display: flex; align-items: center; gap: 6px; padding: 6px 10px; font-size: 0.75rem; border-radius: 6px;">
                                    <i class="fa-solid fa-up-right-from-square" style="font-size: 0.75rem;"></i> Catálogo
                                </a>
                                <button class="btn-secondary btn-sm" onclick="copyToClipboard('${window.location.origin}/catalog/${store.id}', 'Link do catálogo copiado!')" title="Copiar link do catálogo" style="display: flex; align-items: center; gap: 6px; padding: 6px 10px; font-size: 0.75rem; border-radius: 6px;">
                                    <i class="fa-solid fa-copy" style="font-size: 0.75rem;"></i> Link
                                </button>
                            </div>
                        </div>
                        ${statusHtml}
                    </div>
                `;
            }

            // Also show instances NOT linked to any store (Owner and Admin only)
            if (currentUser.role === 'owner' || currentUser.role === 'admin') {
                const linkedInstIds = stores.map((s: any) => s.instancia_id).filter((id: any) => !!id);
                const redundantInstIds = allInstances.filter(i => i.lojaId).map(i => i.id);
                const allLinkedIds = new Set([...linkedInstIds, ...redundantInstIds]);

                const unlinkedInstances = allInstances.filter(i => !allLinkedIds.has(i.id));

                if (unlinkedInstances.length > 0) {
                    html += `
                        <div class="card" style="margin-top: 2rem; border: 1px dashed rgba(255,255,255,0.2); background: rgba(255,255,255,0.02);">
                            <h4 style="margin-bottom: 1rem; color: var(--text-muted);"><i class="fa-solid fa-link-slash"></i> Instâncias não vinculadas a lojas</h4>
                            <div style="display: grid; grid-template-columns: repeat(auto-fill, minmax(300px, 1fr)); gap: 1rem;">
                    `;

                    for (const inst of unlinkedInstances) {
                        let isOnline = false;
                        try {
                            const status = await evolutionApi.getInstanceStatus(inst.nome);
                            isOnline = status.connected;
                        } catch (e) { }

                        html += `
                            <div style="background: rgba(255,255,255,0.05); padding: 1rem; border-radius: 8px;">
                                <div style="display:flex; justify-content:space-between; align-items:center;">
                                    <strong>${inst.nome}</strong>
                                    <span class="badge ${isOnline ? 'success' : 'warning'}">${isOnline ? 'Online' : 'Offline'}</span>
                                </div>
                                <p style="font-size:0.75rem; color: var(--text-muted); margin-top: 0.5rem;">Vá em Configurações > Lojas para vincular esta instância a uma unidade.</p>
                            </div>
                        `;
                    }

                    html += `</div></div>`;
                }
            }

            container.innerHTML = html;
        } catch (error) {
            console.error('Error setting up Store statuses:', error);
            container.innerHTML = `
                <div class="card" style="margin-top: 1.5rem; background: var(--surface-hover);">
                    <p style="color: var(--danger);">Erro ao carregar os status integrados.</p>
                </div>
            `;
        }
    }
};
